### ISSUE TITLE
Game Tree build is rounding bet sizes down, instead to nearest

### ISSUE THREAD

**Issue by maosatgithub** [bupticybee/TexasSolver#106]
Of course that's also a question of design, but I would think that counting to the nearest would be more intuitive. I found this when constructing the example for #105, so when using 33% instead of 34% I finally used there, the 3-bet into a pot of 15 would be 4 instead of 5.

**Comment by maosatgithub** [comment]
Sorry, I think I made a mistake here, I cannot reproduce it now.

**Comment by bupticybee** [comment]
Okay, I will still check it. Thanks for the test data
