### ISSUE TITLE
Error when launching TexasSolverGui.exe

### ISSUE THREAD

**Issue by TolstayaKobra** [bupticybee/TexasSolver#113]
Hello, i have Windows 10 on VirtualBox and when i launch TexasSolverGui.exe i get a bunch of errors: 
1. The code execution cannot proceed because MSVCP140.dll was not found. Reinstalling the program may fix this problem. 
2. The code execution cannot proceed because VCOMP140.dll was not found. Reinstalling the program may fix this problem. 
3. The code execution cannot proceed because VCRUNTIME140.dll was not found. Reinstalling the program may fix this problem. 
4. The code execution cannot proceed because MSVCP140.dll was not found. Reinstalling the program may fix this problem. 
I already tried to reinstall the program, but nothing changed. Any ideas? I will be thankful.

**Comment by TolstayaKobra** [comment]
Windows 10 is 64 bit

**Comment by bupticybee** [comment]
> Windows 10 is 64 bit

Ok, It's actually a common problem, please download latest microsoft runtime to solve this problem.

**Comment by tfjwww** [comment]
I've downloaded newest release several times and am getting error from above: 2. The code execution cannot proceed because VCOMP140.dll was not found. Reinstalling the program may fix this problem.

**Comment by bupticybee** [comment]
> I've downloaded newest release several times and am getting error from above: 2. The code execution cannot proceed because VCOMP140.dll was not found. Reinstalling the program may fix this problem.

You need to download the latest microsoft runtime.

**Comment by bupticybee** [comment]
Closing because issue is not active for too long. Reopen if necessary.
