### ISSUE TITLE
cannot set_raise_limit with console version

### ISSUE THREAD

**Issue by kncesarini** [bupticybee/TexasSolver#116]
From what I can find it doesn't seem to be possible to set this parameter when using the console version.

```
set_raise_limit 3
command not recognized: set_raise_limit
```

There is no matching command in here:
https://github.com/bupticybee/TexasSolver/blob/console/src/tools/CommandLineTool.cpp

So i assume this means currently it will always use the default value 4 from here:
https://github.com/bupticybee/TexasSolver/blob/console/include/tools/CommandLineTool.h

**Comment by bupticybee** [comment]
Ok I see, it's a bug.
I see you have post a pr, I will review and merge them

**Comment by bupticybee** [comment]
#117 merged. Thanks for contribution.

**Comment by bupticybee** [comment]
This issue is considered solved by #117. Closing.

Reopen if necessary
