### ISSUE TITLE
windows 32x

### ISSUE THREAD

**Issue by TrollKentWolf** [bupticybee/TexasSolver#123]
Hi,i have Windows 7 32bit and when open TexasSolverGui i get error:the version of this file is not compatible with the version of Windows you`re running.Check your computer`s system information to see whether you need an x86(32-bit) or x64(64-bit) version of the program, and thren contact the software publisher.

**Comment by bupticybee** [comment]
I have never tested on win32 before, and I don't have a win32 PC, so I'm afraid I can't help.

**Comment by bupticybee** [comment]
Closing. Reopen if necessary.
