### ISSUE TITLE
Understanding the card5_dic_sorted.txt file

### ISSUE THREAD

**Issue by silentdiverchris** [bupticybee/TexasSolver#124]
A query rather than an issue really, but I'm trying to get my head around what the 2.6 million lines in this file are. At first I assumed it was all possible 5 card boards but 52x51x50x49x48 is 311 million, not 2.6 million so surely it can't be all possible boards, so what is that set / the inclusion criteria for it ?

Deep poker strategy isn't exactly my field so please excuse my ignorance, but if somebody could tell me what those 2.6 million lines represent, where my maths is wrong or whatever else it is I'm not understanding; I'd appreciate it, thanks.

**Comment by yffbit** [comment]
should be combination C(52,5) rather than permutation A(52,5)

**Comment by silentdiverchris** [comment]
> should be combination C(52,5) rather than permutation A(52,5)

Thanks, could you expand on that a little please ?

**Comment by yffbit** [comment]
A(52,5)=52*51*50*49*48
C(52,5)=52*51*50*49*48/(5*4*3*2*1)
the strength of different permutations of 5 cards are same

**Comment by silentdiverchris** [comment]
Oh of course, removing the cases where the cards are the same but the order is different. That explains the 2.6 million / 131 million discrepancy. Thank you.

**Comment by bupticybee** [comment]
> A(52,5)=52*51*50*49*48 C(52,5)=52*51*50*49*48/(5*4*3*2*1) the strength of different permutations of 5 cards are same

Thanks very much for the explain.
