### ISSUE TITLE
Specifying hole cards rather than ranges for post-flop

### ISSUE THREAD

**Issue by silentdiverchris** [bupticybee/TexasSolver#128]
Hi, I've been trying to solve for specific hole cards rather than ranges for post-flop, eg "KhJd" rather than "KJo", is this possible ? - thanks.

**Comment by bupticybee** [comment]
> Hi, I've been trying to solve for specific hole cards rather than ranges for post-flop, eg "KhJd" rather than "KJo", is this possible ? - thanks.

Yes, it's possible, community is now working on this subject.

**Comment by silentdiverchris** [comment]
Ok, thanks.
