### ISSUE TITLE
如何解决：“由于找不到VCOMP140.DLL，无法继续执行代码。重新安装程序可能会解决此问题”

### ISSUE THREAD

**Issue by qie2003** [bupticybee/TexasSolver#134]
大神您好：我解压完texassolver 0.2.0 windows版本，点击texassolvergui.exe，弹出提示框“由于找不到VCOMP140.DLL，无法继续执行代码。重新安装程序可能会解决此问题”。
我重新安装了两遍，仍无法解决，向您求助，麻烦您帮我看看，谢谢！
还是说这个软件只能用命令提示符使用？

期待您的回复！谢谢！

**Comment by bupticybee** [comment]
安装最新的微软runtime应该可以解决呀，如果不能解决说明你没装好，或者环境乱了，其他人都是通过安装runtime解决的这个问题。

**Comment by qie2003** [comment]
谢谢大神，我解决了，我昨晚下的runtime不对。另外，也给后来的小伙伴们分享下“mircrosoft visual studio for office runtime”的官方下载地址
https://learn.microsoft.com/zh-CN/cpp/windows/latest-supported-vc-redist?view=msvc-170

**Comment by bupticybee** [comment]
> 谢谢大神，我解决了，我昨晚下的runtime不对。另外，也给后来的小伙伴们分享下“mircrosoft visual studio for office runtime”的官方下载地址 https://learn.microsoft.com/zh-CN/cpp/windows/latest-supported-vc-redist?view=msvc-170

好的，issue已经解决，closing
