### ISSUE TITLE
Turn and River Card

### ISSUE THREAD

**Issue by marcus2343** [bupticybee/TexasSolver#138]
Hello, 

When I run the solver for the flop, I cannot continue the decision nodes past the flop. Is this a bug or an element not included yet? 

And do these turn or river drop-down menus work?

![image](https://user-images.githubusercontent.com/116376188/197243274-d229789d-5d21-4c88-bc7e-e7a2443c2eeb.png)

Thank you,

**Comment by bupticybee** [comment]
> When I run the solver for the flop, I cannot continue the decision nodes past the flop. Is this a bug or an element not included yet?
> 
> And do these turn or river drop-down menus work?

It's a QT problem, you need to double click the node the expand it. It surely go past flop.

**Comment by marcus2343** [comment]
Thank you! 

For others with the same issue, you must double-click the decision-ending node for the turn or river tree to appear. The photo below shows "IP Call" without a continuing tree but once you double click it will appear. 

![image](https://user-images.githubusercontent.com/116376188/197547253-02d7090f-5daf-4253-adc8-5a28c099b505.png)
