### ISSUE TITLE
目前的版本每一条街都需要单独解算吗？

### ISSUE THREAD

**Issue by kntism** [bupticybee/TexasSolver#148]
感谢提供这么好的工具！
想问一下，目前版本是不是每一条街都需要单独解算？
比如：公共牌如果设置三张，解算结果就只包含flop的解算结果；然后需要设置公共牌为四张，并重新结算才能得到turn的结果？

**Comment by bupticybee** [comment]
> 感谢提供这么好的工具！ 想问一下，目前版本是不是每一条街都需要单独解算？ 比如：公共牌如果设置三张，解算结果就只包含flop的解算结果；然后需要设置公共牌为四张，并重新结算才能得到turn的结果？

并不是，这是一个界面问题，一些节点需要双击才能展开，解算都是一直算到river的，cfr的原理决定了不能单独解算某一条街

**Comment by kntism** [comment]
根据你的提示，我已经找到了，谢谢！
