### ISSUE TITLE
Preflop ranges

### ISSUE THREAD

**Issue by eonia89** [bupticybee/TexasSolver#150]
Can I ask for a sneaky share of preflop ranges for my pure curiosity?

Thanks.

**Comment by bupticybee** [comment]
preflop ranges comes with the solver. You can find them in ranges folder.

**Comment by eonia89** [comment]
@bupticybee 
I am aware of the ranges which came along with the solver. However, it looks like it has 'vs 3bet+' strategy without RFIs.
Is there anyway that I can see those ranges or you do not take them into account in the scope of this project?

**Comment by bupticybee** [comment]
So far no. I take them from a 3rd party project.
