### ISSUE TITLE
allin threshold

### ISSUE THREAD

**Issue by nguyenviettuan96** [bupticybee/TexasSolver#154]
Could u let me know what is allin threshold , use_isomorphism and dumps_round please ? Thank you

**Comment by bupticybee** [comment]
Allin threshold means after how many percent of pot, the tree building algorithm would turn any bet/raise exceeds that percent of pot into an allin.

use_isomorphism is a optimization option, if on, the solver would run faster in most cases.

dumps_round means how many round would you want to save in the dump json file.  Normally 1~2 is enough, set to 3  could cause slow dump.

Hope that helps.

**Comment by nguyenviettuan96** [comment]
"All-in threshold means after how many percent of pot" I think it is how many percent of stack, the bet will be an all-in because an all-in is depend on the stack. For example, if the stack is 100bb but the bet is 90bb, so 90/100 > allin_thres, the bet should be an all-in. Is that right? Thank you

**Comment by nguyenviettuan96** [comment]
thank you very much
