### ISSUE TITLE
how can I reduce solving time?

### ISSUE THREAD

**Issue by nguyenviettuan96** [bupticybee/TexasSolver#158]
Happy new year from vietnam. Do you have any idea to run solver on GPU ?

**Comment by bupticybee** [comment]
Running on GPU is a great idea, however I'm afraid noone is able to get a good speedup from running cfr algorithms on gpu at this point of time. Read a few paper about it, for now there is no such algorithm that can run cfr on GPU and get a good speedup.

**Comment by Thomas-MMJ** [comment]
> Running on GPU is a great idea, however I'm afraid noone is able to get a good speedup from running cfr algorithms on gpu at this point of time. Read a few paper about it, for now there is no such algorithm that can run cfr on GPU and get a good speedup.

I believe you are mistaken, 

see

> As the game’s size grows bigger, the difference between the CPU and GPU implementation becomes more and more apparent. On Goofspiel 3, the GPU implementation is about five times faster than the CPU implementation. On Goofspiel 4, the GPU implementation is about 47 times faster than the CPU implementation.

https://cent.felk.cvut.cz/courses/GPU/archives/2020-2021/W/rudolja1/

Source code, development report, etc. are all available at the link.

Same author - code is in git, is Vanilla CFR, supports multiple GPUs,

https://github.com/janrvdolf/gpucfr

**Comment by Thomas-MMJ** [comment]
This might be of interest, a discussion by a pytorch dev on GPU optimization,

https://horace.io/brrr_intro.html

**Comment by deflexor** [comment]
Hi, as an option I guess is to get more CPUs and cores instead of GPU ?

**Comment by bupticybee** [comment]
> Hi, as an option I guess is to get more CPUs and cores instead of GPU ?

For now, in this project, yes.
