### ISSUE TITLE
Qt version

### ISSUE THREAD

**Issue by nguyenviettuan96** [bupticybee/TexasSolver#160]
I try to rewrite this tool for only river round, that can run in real time with immediate input(not exec from txt file) and met some errors about QString. Could you let me know your Qt version?. Thank you

**Comment by bupticybee** [comment]
As described in readme. I use QT 5.1.0 (opensourced edition) to build the GUI version. For the console version, I use Mingw + CMake.

**Comment by nguyenviettuan96** [comment]
when I test, I checked that this function: this->compairer = make_shared<Dic5Compairer>(compairer_file,compairer_file_lines); in PokerSolver.cpp consumes so much time. Could you give me an idea to reduce time?

**Comment by bupticybee** [comment]
> when I test, I checked that this function: this->compairer = make_shared(compairer_file,compairer_file_lines); in PokerSolver.cpp consumes so much time. Could you give me an idea to reduce time?. I hope your next version will be faster if solving this problem

Check GUI branch, this is already solved.

**Comment by nguyenviettuan96** [comment]
Thank you. That is unbelievable, master branch cost me so much time

**Comment by bupticybee** [comment]
> Thank you. That is unbelievable, master branch cost me so much time. You know, when I ask to train on GPU, that is not a way to solve problem.

So is this issue solved?

**Comment by nguyenviettuan96** [comment]
yes of course
