### ISSUE TITLE
River data not included in json output file

### ISSUE THREAD

**Issue by EddieMataEwy** [bupticybee/TexasSolver#164]
The generated json file when exported from GUI with default setting and parameters does not include river data. Maybe this is normal behavior because of file size. If this is the case, you can mark the issue as closed.

**Comment by bupticybee** [comment]
> The generated json file when exported from GUI with default setting and parameters does not include river data. Maybe this is normal behavior because of file size. If this is the case, you can mark the issue as closed.

As I mentioned in the video, by default export file would only contain 2 rounds of data (flop,turn), if you want to dump river strategy, you need to mannually set round to 3 in setting.

**Comment by EddieMataEwy** [comment]
Sorry, I must have missed it.
Thank you!.
