### ISSUE TITLE
"Persional edition"

### ISSUE THREAD

**Issue by Dunge** [bupticybee/TexasSolver#175]
There's just a few sentences on your website, and one of them contains a typo. Doesn't look that inspiring.

**Comment by bupticybee** [comment]
Glad you point it out. Now it's fixed at https://github.com/bupticybee/texassolver_page/commit/6882042ed304495e547b78349c05d06c289cd407 .

Not really sure what you mean by inspiring, what I can say is any kind of contribution is welcome.
