### ISSUE TITLE
我想请问一下如何对默认的范围文件夹路径进行修改

### ISSUE THREAD

**Issue by doufudada** [bupticybee/TexasSolver#178]
mac版本默认读取的目录是根目录，我希望默认读取的目录就像演示视频一样直接进入range目录，想请问下作者我应该如何修改，感谢！

<img width="272" alt="image" src="https://github.com/bupticybee/TexasSolver/assets/59639190/6be10459-01ed-4eea-b840-24e86adbdab6">

**Comment by bupticybee** [comment]
Mac可以直接把参数文件拖拽到主界面，会自动读取，你可以试试看

**Comment by doufudada** [comment]
我尝试了一下，没有自动读取，还有其他可行的方式吗

**Comment by bupticybee** [comment]
> 我尝试了一下，没有自动读取，还有其他可行的方式吗

Hmm，我表达的有问题，是打开range选择页面，然后拖拽进去，不是直接在主页面拖拽

**Comment by doufudada** [comment]
我直接进行拖拽，好像也不可行







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bupticybee/TexasSolver"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月12日(星期二) 上午8:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [bupticybee/TexasSolver] 我想请问一下如何对默认的范围文件夹路径进行修改 (Issue #178)





  
我尝试了一下，没有自动读取，还有其他可行的方式吗
  
Hmm，我表达的有问题，是打开range选择页面，然后拖拽进去，不是直接在主页面拖拽

**Comment by bupticybee** [comment]
> 我直接进行拖拽，好像也不可行
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "bupticybee/TexasSolver" ***@***.***&gt;; 发送时间:&nbsp;2023年9月12日(星期二) 上午8:39 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [bupticybee/TexasSolver] 我想请问一下如何对默认的范围文件夹路径进行修改 (Issue #178) 我尝试了一下，没有自动读取，还有其他可行的方式吗 Hmm，我表达的有问题，是打开range选择页面，然后拖拽进去，不是直接在主页面拖拽 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

不应该呀，在这种情况下，试试打开range文件，直接复制进来吧

**Comment by doufudada** [comment]
直接打开range文件是可以复制成功的，但是这样的话，感觉使用起来会麻烦许多，能否麻烦您帮我拍个视频演示一下？看看您是怎么操作的，感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bupticybee/TexasSolver"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月12日(星期二) 下午4:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [bupticybee/TexasSolver] 我想请问一下如何对默认的范围文件夹路径进行修改 (Issue #178)





  
我直接进行拖拽，好像也不可行
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "bupticybee/TexasSolver" @.&gt;; 发送时间:&nbsp;2023年9月12日(星期二) 上午8:39 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [bupticybee/TexasSolver] 我想请问一下如何对默认的范围文件夹路径进行修改 (Issue #178) 我尝试了一下，没有自动读取，还有其他可行的方式吗 Hmm，我表达的有问题，是打开range选择页面，然后拖拽进去，不是直接在主页面拖拽 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
不应该呀，在这种情况下，试试打开range文件，直接复制进来吧

**Comment by bupticybee** [comment]
> 直接打开range文件是可以复制成功的，但是这样的话，感觉使用起来会麻烦许多，能否麻烦您帮我拍个视频演示一下？看看您是怎么操作的，感谢！
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "bupticybee/TexasSolver" ***@***.***&gt;; 发送时间:&nbsp;2023年9月12日(星期二) 下午4:51 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [bupticybee/TexasSolver] 我想请问一下如何对默认的范围文件夹路径进行修改 (Issue #178) 我直接进行拖拽，好像也不可行 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "bupticybee/TexasSolver" @.&gt;; 发送时间:&nbsp;2023年9月12日(星期二) 上午8:39 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [bupticybee/TexasSolver] 我想请问一下如何对默认的范围文件夹路径进行修改 (Issue #178) 我尝试了一下，没有自动读取，还有其他可行的方式吗 Hmm，我表达的有问题，是打开range选择页面，然后拖拽进去，不是直接在主页面拖拽 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt; 不应该呀，在这种情况下，试试打开range文件，直接复制进来吧 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

我回头找个时间check下

**Comment by bupticybee** [comment]
https://github.com/bupticybee/TexasSolver/assets/9393610/46d4c7bb-d892-4190-8c22-09e3c7e870eb

**Comment by doufudada** [comment]
已收到，解决了，感谢！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年9月12日(星期二) 下午5:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [bupticybee/TexasSolver] 我想请问一下如何对默认的范围文件夹路径进行修改 (Issue #178)





 
https://github.com/bupticybee/TexasSolver/assets/9393610/46d4c7bb-d892-4190-8c22-09e3c7e870eb

**Comment by bupticybee** [comment]
关闭issue，因为issue已经解决
