### ISSUE TITLE
 Can I add additional bet sizings?

### ISSUE THREAD

**Issue by zikkuratti** [bupticybee/TexasSolver#180]
Hello. Can I add additional bet sizings? For example, not just two, one and all-in, but say four or five sizings. Without significant refactoring of the current code? If not, could you please suggest which file to start reviewing? I have some knowledge of C++ and I'll try to implement this to make a merge soon?

**Comment by bupticybee** [comment]
> Hello. Can I add additional bet sizings? For example, not just two, one and all-in, but say four or five sizings. Without significant refactoring of the current code? If not, could you please suggest which file to start reviewing? I have some knowledge of C++ and I'll try to implement this to make a merge soon?

you can just add bet size in the GUI, you don't even need to modify the code.

Use space to seperate different bet sizes.

**Comment by zikkuratti** [comment]
holy thx
