### ISSUE TITLE
Warning: QMetaObject::connectSlotsByName: No matching signal for on_XXX_YYY()

### ISSUE THREAD

**Issue by ruimaciel** [bupticybee/TexasSolver#183]
The following warnings are emitted when launching the app:

```
16:22:32: Starting /home/rui/develop/C++/TexasSolver/build/TexasSolverGui-Desktop_Qt_5_15_2_GCC_64bit/Debug/TexasSolverGui...
Warning: QMetaObject::connectSlotsByName: No matching signal for on_import_params() ((null):0, (null))
Warning: QMetaObject::connectSlotsByName: No matching signal for on_export_params() ((null):0, (null))
Warning: QMetaObject::connectSlotsByName: No matching signal for on_clear_all() ((null):0, (null))
Warning: QMetaObject::connectSlotsByName: No matching signal for on_ip_range(QString) ((null):0, (null))
```

These warnings are caused by the slots' naming convention conflicting with Qt's autoconnect feature.  See [this Qt forum post](https://forum.qt.io/topic/139073/no-matching-signal-and-no-matching-member-function-for-call-to-connect/2).

The goal of this issue is to prevent the app from emitting these warnings.

**Comment by bupticybee** [comment]
I see, thanks for the knowledge and the fix~
