### ISSUE TITLE
关于`console_solver`指令 Regarding `console_solver` command

### ISSUE THREAD

**Issue by poju3185** [bupticybee/TexasSolver#193]
大神你好，请问是否有`console_solver`指令相关的文档。
我想要在解算完后不输出JSON，直接在console查看结果，但是不知道指令该如何输入。

Could someone please provide any documentation on the `console_solver` command? I would like to view the results directly in the console without outputting JSON after solving, but I'm not sure how to input the command.

**Comment by bupticybee** [comment]
> 大神你好，请问是否有`console_solver`指令相关的文档。 我想要在解算完后不输出JSON，直接在console查看结果，但是不知道指令该如何输入。
> 
> Could someone please provide any documentation on the `console_solver` command? I would like to view the results directly in the console without outputting JSON after solving, but I'm not sure how to input the command.

你好，没有支持在console里查看结果的功能，不好意思啊

**Comment by poju3185** [comment]
了解，谢谢你。另外想请问下，有支持解算单一round的功能吗？

**Comment by bupticybee** [comment]
> 了解，谢谢你。另外想请问下，有支持解算单一round的功能吗？

原理上cfr必须从current round解到river，但是你可以减小byeond current round的raise size等等减少树的大小。比如你解算flop的时候，turn和river就只用一个size，这样就可以满足本轮精度的同事减少内存占用。

**Comment by poju3185** [comment]
明白了，感謝大神。
