### ISSUE TITLE
OOP range doesn't match

### ISSUE THREAD

**Issue by fmo-mt** [bupticybee/TexasSolver#198]
preflop setting like:
<img width="361" alt="image" src="https://github.com/bupticybee/TexasSolver/assets/118255577/61792cd8-83f4-43be-bc78-d089069573b2">

solver result:
<img width="647" alt="image" src="https://github.com/bupticybee/TexasSolver/assets/118255577/18c308b4-2996-455d-a457-0031466aac8f">

As you can see, we missed the AX which is set in preflop range

**Comment by bupticybee** [comment]
Range has to substract board card, normal situation.

**Comment by bupticybee** [comment]
> preflop setting like: <img alt="image" width="361" src="https://private-user-images.githubusercontent.com/118255577/329609412-61792cd8-83f4-43be-bc78-d089069573b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzODUzNzIsIm5iZiI6MTcxNTM4NTA3MiwicGF0aCI6Ii8xMTgyNTU1NzcvMzI5NjA5NDEyLTYxNzkyY2Q4LTgzZjQtNDNiZS1iYzc4LWQwODkwNjk1NzNiMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMFQyMzUxMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZWZiMjMyYTQzZjIwZDAyM2M4N2RhZDBiNjU0YWYzZjRjZDA1NjEwOTIyMjM0MDQzZTQzMGQzNTk2NTJiZTdiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BlEMXgTI3eDQ_k0IOa7uDfd7UCwcSy2s6DL6cTvI2cs">
> 
> solver result: <img alt="image" width="647" src="https://private-user-images.githubusercontent.com/118255577/329609639-18c308b4-2996-455d-a457-0031466aac8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzODUzNzIsIm5iZiI6MTcxNTM4NTA3MiwicGF0aCI6Ii8xMTgyNTU1NzcvMzI5NjA5NjM5LTE4YzMwOGI0LTI5OTYtNDU1ZC1hNDU3LTAwMzE0NjZhYWM4Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMFQyMzUxMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNTEwOGU3ZTA3YTcyYmZiZmRkNmFhNjZhMWQxZTEwZmU0MWY5MzMwZGQ1MDZmZTU2OThjOTk1MWZmOTQ0ODg1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VwOzAaLjoMzywfUNgjTQ65UDFmo_8TwkCZuy_gvU-58">
> 
> As you can see, we missed the AX which is set in preflop range

Could you provide the config?

**Comment by bupticybee** [comment]
Could be a bug or something

**Comment by fmo-mt** [comment]
Oh I reopened the App, and the error's gone...could be a bug though, thanks for reply

**Comment by bupticybee** [comment]
> Oh I reopened the App, and the error's gone...could be a bug though, thanks for reply

Okay, thanks for the report anyways~
