### ISSUE TITLE
Error  Card length incorrect: 0 in windows

### ISSUE THREAD

**Issue by deslieh** [bupticybee/TexasSolver#199]
![1718074808629](https://github.com/bupticybee/TexasSolver/assets/30916979/81a496b9-4a0c-48ed-87c5-63253b8fcc61)

**Comment by timcopelandoh** [comment]
Having the same issue (mac). Did you ever figure it out?

**Comment by Takumi-trbl** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by bupticybee** [comment]
> Having the same issue (mac). Did you ever figure it out?
> 
> Edit: from an earlier issue - I think this happens, when the "Build Tree" was not done before "Start Solving", independent of OS.

If you build tree before start solving, did it still occur?

**Comment by timcopelandoh** [comment]
> > Having the same issue (mac). Did you ever figure it out?
> > Edit: from an earlier issue - I think this happens, when the "Build Tree" was not done before "Start Solving", independent of OS.
> 
> If you build tree before start solving, did it still occur?

Nope, that resolved the issue. Working fine now.

**Comment by bupticybee** [comment]
Closing this issue since it's solved.
