### ISSUE TITLE
Saving evs in output file

### ISSUE THREAD

**Issue by jakobGTO** [bupticybee/TexasSolver#202]
Hello

When saving a solution to json only the strategy seems to be saved, not the evs, equity etc. Is it possible to save these to json aswell?

**Comment by Takumi-trbl** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by bupticybee** [comment]
> Hello
> 
> When saving a solution to json only the strategy seems to be saved, not the evs, equity etc. Is it possible to save these to json aswell?

Yeah that's possible,need a slight modification in code though.

**Comment by jakobGTO** [comment]
> > Hello
> > When saving a solution to json only the strategy seems to be saved, not the evs, equity etc. Is it possible to save these to json aswell?
> 
> Yeah that's possible,need a slight modification in code though.

Ok thank you. Im new to this project could you point me to where i have to make this modification.

**Comment by jakobGTO** [comment]
solved by adding `(*retval)["evs"] = trainable->dump_evs();` to the `PCfrSolver::reConvertJson` method
