### ISSUE TITLE
缺少dll

### ISSUE THREAD

**Issue by JohnnyLeung996** [bupticybee/TexasSolver#27]
windows找不到libgcc_s_seh-1.dll, libwinpthread-1.dll, libgomo-1.dll, libstdc++-6.dll

需要装什么库？

**Comment by bupticybee** [comment]
这个是我在编译的时候忘记链接这些库了，我晚上寻求一下解决方案

**Comment by JohnnyLeung996** [comment]
好的，还有在windows上编译不了

CMake Error at CMakeLists.txt:2 (project):
  The CMAKE_C_COMPILER:

    /usr/local/Cellar/gcc@7/7.5.0_3/bin/gcc-7

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


CMake Error at CMakeLists.txt:2 (project):
  The CMAKE_CXX_COMPILER:

    /usr/local/Cellar/gcc@7/7.5.0_3/bin/g++-7

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.

**Comment by JohnnyLeung996** [comment]
应该也是缺少库吧

**Comment by bupticybee** [comment]
I see, 这个需要手动在clion中把编译器选成自己下载的mingw

**Comment by bupticybee** [comment]
我默认上传的Clion 配置文件是mac用的，/usr/local/Cellar/gcc@7/7.5.0_3/bin/g++-7 这个也很明显是mac的路径，win的路径不长这样，你可能要手动改下

**Comment by JohnnyLeung996** [comment]
我找到了一个类似的路径H:\Tools\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\lib\gcc\x86_64-w64-mingw32\8.1.0
但是里面没有bin文件夹，不知道g++-7是什么

![1](https://user-images.githubusercontent.com/86847085/130433108-d55b1242-2905-41ca-b186-b6e9178cc2cc.png)

**Comment by bupticybee** [comment]
> 我找到了一个类似的路径H:\Tools\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\lib\gcc\x86_64-w64-mingw32\8.1.0
> 但是里面没有bin文件夹，不知道g++-7是什么
> 
> ![1](https://user-images.githubusercontent.com/86847085/130433108-d55b1242-2905-41ca-b186-b6e9178cc2cc.png)

就只需要在clion中把compiler设置成mingw就行，其他的都不需要改，我自然对你的本地文件结构也不了解

**Comment by bupticybee** [comment]
这个项目已经有两三个人在win上编译成功了，所以肯定是可以编译的

**Comment by JohnnyLeung996** [comment]
我用的就是mingw，把CMake options删掉就能编译了，但是编译出来的也是缺少libgcc_s_seh-1.dll, libwinpthread-1.dll, libgomo-1.dll, libstdc++-6.dll

![1](https://user-images.githubusercontent.com/86847085/130439887-c5b5967b-c192-4629-bf87-a874db3f51d3.png)
![2](https://user-images.githubusercontent.com/86847085/130439890-b9ac7ef2-fdff-47ad-b5f3-503402bfe341.png)
![3](https://user-images.githubusercontent.com/86847085/130439895-0ce76bc2-1110-4270-b5ea-a2fac75b9aec.png)
![4](https://user-images.githubusercontent.com/86847085/130439899-e35abd2b-6496-4495-8b9e-10e921513e20.png)

**Comment by bupticybee** [comment]
> 我用的就是mingw，把CMake options删掉就能编译了，但是编译出来的也是缺少libgcc_s_seh-1.dll, libwinpthread-1.dll, libgomo-1.dll, libstdc++-6.dll
> 
> ![1](https://user-images.githubusercontent.com/86847085/130439887-c5b5967b-c192-4629-bf87-a874db3f51d3.png)
> ![2](https://user-images.githubusercontent.com/86847085/130439890-b9ac7ef2-fdff-47ad-b5f3-503402bfe341.png)
> ![3](https://user-images.githubusercontent.com/86847085/130439895-0ce76bc2-1110-4270-b5ea-a2fac75b9aec.png)
> ![4](https://user-images.githubusercontent.com/86847085/130439899-e35abd2b-6496-4495-8b9e-10e921513e20.png)

你直接使用IDE里边的run option可以用么？这个应该是肯定可以用的才对呀，好多其他人都是这么跑起来的

**Comment by bupticybee** [comment]
你直接用IDE里边的zhe这个

![截屏2021-08-23 下午9 06 39](https://user-images.githubusercontent.com/9393610/130452413-ee671134-1112-4ebf-8c50-9b0dc12d3fd2.png)

跑得起来么？

**Comment by bupticybee** [comment]
Closing because the problem is solved by 0.1.0 release

**Comment by JohnnyLeung996** [comment]
非常抱歉，一直没看消息，都可以了。

**Comment by bupticybee** [comment]
> 非常抱歉，一直没看消息，都可以了。

赞～感谢使用，欢迎提意见和建议
