### ISSUE TITLE
Status and GUI

### ISSUE THREAD

**Issue by dev-ns8** [bupticybee/TexasSolver#3]
Hello,

Is this project still actively being worked on? Is there a status on the GUI for C++ version?

Thanks!

**Comment by bupticybee** [comment]
It's still very active, most commits  happened in https://github.com/bupticybee/TexasSolver/tree/iso branch, I merge the branch to master whenever it becomes stable.

I'm still working on the command line interfaces, it's not finished. There are plans for gui, but It will be server months before it's finished.

**Comment by bupticybee** [comment]
Problem considered solved, closing

**Comment by ophicleidon** [comment]
>  There are plans for gui, but It will be server months before it's finished.

Hi,
I was considering starting work on a UI on my own. Do you already have any code for the UI I could contribute to?

**Comment by bupticybee** [comment]
> I do understand CFR, but I was planning to use the UPI interface and write the UI in js. The UI would be open source.

I didn't implement UPI interface sadly, so you are planning to ad UPI interface for this project? I'm a little bit confused here.
