### ISSUE TITLE
memory usage tree compression

### ISSUE THREAD

**Issue by LetterRip** [bupticybee/TexasSolver#33]
Are you using any tree or other memory compression tricks?

Compression is mentioned in the logs of jesolver (By the developer who did Cephesus)

https://jesolver.com/cmdref.html#set_compression
https://jesolver.com/download/free/changelog.txt

He has some CFR compression work but it isn't clear if it applies - uses average strategy
https://jeskola.net/cfr/

https://jeskola.net/cfr/dcfu/
https://jeskola.net/cfr/avgstr/

Simplepostflop mentions tree compression,

"Simple Postflop Solver has 3 different algorithms (A1, A2, A3) and SPF A1 algorithm could use different degrees of tree compression in the RAM."

https://simplepoker.com/en/News/Fair_Performance_Comparison_of_Simple_Postflop_and_PioSolver_56

". Also, algorithm can now use compression of strategy tree in RAM 2x, 3x and 4x times, which allows to run much more complex trees than previously your PCs allowed."

https://forumserver.twoplustwo.com/167/poker-software/simple-poker-best-gto-solvers-preflop-postflop-holdem-omaha-2-way-mw-amp-gto-tools-1518064/index8.html

**Comment by bupticybee** [comment]
I will look into that, thanks for the tips
