### ISSUE TITLE
Segfault after build install

### ISSUE THREAD

**Issue by noname72** [bupticybee/TexasSolver#37]
Hello, thank you for this project!
I have a problem when try to build and start "make install" from master - it fails on test, and can't start solver (segfault).
If you need any additional info - please let me know.
CentOS 8.1 4.18.0-193.14.2.el8_2.x86_64
Name         : cmake
Version      : 3.18.2
Release      : 11.el8_4

Name         : make
Epoch        : 1
Version      : 4.2.1
Release      : 10.el8

Name         : gcc
Version      : 8.4.1
Release      : 1.el8

What I'm tried: 
```
  65  2021-08-30 09:38:02 root pip3.9 install cmake --upgrade
   72  2021-08-30 09:39:56 root yum install gcc
   73  2021-08-30 09:40:19 root yum install gcc-c++
   74  2021-08-30 09:40:29 root cmake ..
   82  2021-08-30 09:41:34 root make install
   83  2021-08-30 09:42:32 root ./test
```
  
[root@build]# ./test
```
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from TestCase
[ RUN      ] TestCase.test_poker_solver_bench
[##################################################] 100%
unknown file: Failure
C++ exception with description "[json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal" thrown in the test body.
[  FAILED  ] TestCase.test_poker_solver_bench (45493 ms)
[----------] 1 test from TestCase (45493 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (45493 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] TestCase.test_poker_solver_bench

 **1 FAILED TEST**

```
[root@build]# ./console_solver -i ../resources/text/commandline_sample_input.txt
```
EXEC FROM FILE

<<<START SOLVING>>>
Using 8 threads
Iter: 0
**Segmentation fault (core dumped)**

```

**Comment by bupticybee** [comment]
Did you check this colab? 

https://colab.research.google.com/drive/1NWDb53ypcKpkb3g3orzEBDeHAEkAIC7y

This is the one I use to generate the Linux release. It works 100%.

I didn't try compile it on centos for now. Me and two or three other people have confirmed that it can be compile and run in ubuntu.

And In your log:

```
[root@build]# ./console_solver -i ../resources/text/commandline_sample_input.txt
```

why did you run it in build directory? you need to run it from install

**Comment by noname72** [comment]
thanks for the reply, install directory resolved segfault, my bad
