### ISSUE TITLE
How to run on visual studio and what files should i download ?

### ISSUE THREAD

**Issue by Stark-star** [bupticybee/TexasSolver#4]
I have no idea about all this coding and stuff . Can i just copy paste code is VS19 ? Or what?

**Comment by bupticybee** [comment]
It's a Clion project, you should download latest version of clion and run it.

**Comment by bupticybee** [comment]
Other people get it running on VS but I personally compile it on clion, so clion is recommanded

**Comment by bupticybee** [comment]
If you just want to run a solver, checkout https://github.com/bupticybee/TexasHoldemSolverJava , I made gui for that. This project currently only supports command line I/O, If you have no knowledge of code, it might not suit you well for now

**Comment by Stark-star** [comment]
> If you just want to run a solver, checkout https://github.com/bupticybee/TexasHoldemSolverJava , I made gui for that. This project currently only supports command line I/O, If you have no knowledge of code, it might not suit you well for now

The java version is eating my ram . Whats the requirements for it to run?

**Comment by bupticybee** [comment]
> > If you just want to run a solver, checkout https://github.com/bupticybee/TexasHoldemSolverJava , I made gui for that. This project currently only supports command line I/O, If you have no knowledge of code, it might not suit you well for now
> 
> The java version is killing my cpu . Whats the requirements for it to run?

Yes, java version is not optimized for flop situations, this cpp version is.  You better have a cpu with at least 16 cores and 32G memory. 

The good news is this cpp version is much better, it runs 5x ~ 10x faster than java version, and capable of handling much larger tree, however the bad news is that it will be weeks or even months before fininsh, now just command line version is provided. I still don't have time to write mannual for it, I plan to write the mannual in the following week.

You can wait for the cpp command line version,  before that you can just use java version. Cpp gui version will not be available soon.

**Comment by bupticybee** [comment]
Close this issue bacause its not active for a month.
