### ISSUE TITLE
Some errors on Mac

### ISSUE THREAD

**Issue by GuangshengZ** [bupticybee/TexasSolver#41]
An error has been raised on my Mac:
dyld: Library not loaded: /usr/local/opt/gcc@7/lib/gcc/7/libgomp.1.dylib
Referenced from: /Users/XXXX/poker/TexasSolver-v0/console_solver
Reason: image not found

**Comment by bupticybee** [comment]
This is known bug. Will be fix in the next version.

**Comment by bupticybee** [comment]
Would you please check if the latest 0.1.1 release resolve this issue?

https://github.com/bupticybee/TexasSolver/releases/tag/v0.1.1

**Comment by bupticybee** [comment]
Issue closed because it's not active for a month. Reopen if necessary,
