### ISSUE TITLE
How to import bindSolver ?

### ISSUE THREAD

**Issue by rwayan** [bupticybee/TexasSolver#44]
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    import bindSolver
ModuleNotFoundError: No module named 'bindSolver'

python test.py

**Comment by bupticybee** [comment]
Actually the python interface you are looking at is abandoned, in order to call this solver from python, you can refer to code in 

https://github.com/bupticybee/TexasSolver/blob/master/TexasSolverTechDemo.ipynb

**Comment by bupticybee** [comment]
Closed because this issue has be inactive for too long. Reopen if necessary.
