### ISSUE TITLE
It doesn't work if calculating river only

### ISSUE THREAD

**Issue by arache** [bupticybee/TexasSolver#46]
Input file:

set_pot 100
set_effective_stack 100
set_board Ts,3h,2h,5c,9s
set_range_ip KK
set_range_oop AA,QQ
set_bet_sizes oop,river,allin
set_bet_sizes ip,river,allin
set_allin_threshold 0.67
build_tree
set_thread_num 5
set_accuracy 0.5
set_max_iteration 200
set_print_interval 10
set_use_isomorphism 1
start_solve
set_dump_rounds 2
dump_result output_result.json

output:
EXEC FROM FILE
[##################################################] 100%

Nothing in output.json file

Btw, is there an introduction about all the available commands?

**Comment by bupticybee** [comment]
I will look into it, I didn't test the solver on river-oly situations

**Comment by bupticybee** [comment]
> Input file:
> 
> set_pot 100
> set_effective_stack 100
> set_board Ts,3h,2h,5c,9s
> set_range_ip KK
> set_range_oop AA,QQ
> set_bet_sizes oop,river,allin
> set_bet_sizes ip,river,allin
> set_allin_threshold 0.67
> build_tree
> set_thread_num 5
> set_accuracy 0.5
> set_max_iteration 200
> set_print_interval 10
> set_use_isomorphism 1
> start_solve
> set_dump_rounds 2
> dump_result output_result.json
> 
> output:
> EXEC FROM FILE
> [##################################################] 100%
> 
> Nothing in output.json file
> 
> Btw, is there an introduction about all the available commands?

This is fixed in af31bba911bfbf2d1db5e7b98034e2d238ed92f5, I tested your input file,it works. Please wait for 0.1.1 release

**Comment by bupticybee** [comment]
Closing because this issue has been inactive for too long. Reopen if necessary. 

ps: 0.1.1release probably solved the issue.
