### ISSUE TITLE
windows的一个小问题

### ISSUE THREAD

**Issue by yuwenyang0617** [bupticybee/TexasSolver#49]
在执行的命令行之后，程序似乎只运行了一半，就自动结束了（没有加载进度条）试了几次都是如此

![image](https://user-images.githubusercontent.com/40312147/132944479-ad5fabb6-b2f6-4e64-aea2-248fcf84577d.png)

**Comment by yuwenyang0617** [comment]
> 在执行的命令行之后，程序似乎只运行了一半，就自动结束了（没有加载进度条）试了几次都是如此
> 
> ![image](https://user-images.githubusercontent.com/40312147/132944479-ad5fabb6-b2f6-4e64-aea2-248fcf84577d.png)

当我把一些手牌范围缩短时，这个现象会很有效的解决

**Comment by bupticybee** [comment]
你没有按照我在readme里的步骤执行，你先需要进入项目目录，你这里的目录是c://User/Admin
