### ISSUE TITLE
MinGW-w64 required for console version

### ISSUE THREAD

**Issue by ChChChillian** [bupticybee/TexasSolver#60]
When run on Windows 10 from a vanilla Windows command prompt, console_solver.exe fails to execute with 4 instances of the following error: 
![image](https://user-images.githubusercontent.com/93846800/140627419-a6861217-0317-478b-8e40-9a2d51b687c2.png)

The missing dlls it complains about are:
- libgcc_s_seh-1.dll
- libstdc++6.dll
- libwinpthread-1.dll
- libgomp-1.dll

Execution is successful if run from a MinGW-w64 terminal window.

**Comment by bupticybee** [comment]
Thank you for your reply, seems to be some dependence issue, I will try to resolve them in the future.

**Comment by bupticybee** [comment]
Fixed it just now in this commit https://github.com/bupticybee/TexasSolver/commit/8b27fb35436226f8106cb449561c77e22c69b990 , and I have updated the 0.2.0 release package. I think the problem is gone.
Would you please check if the problem is gone?

**Comment by bupticybee** [comment]
This issue is inactive for too long and is considered solved by release 0.2.0. Reopen if necessary.
