### ISSUE TITLE
About 'set_thread_num'

### ISSUE THREAD

**Issue by MoonBunnyZZZ** [bupticybee/TexasSolver#68]
how many thread num to set?just only 8?I try 1,2,6,10 in resources/text/commandline_sample_input.txt.None work. Error :
terminate called after throwing an instance of 'std::runtime_error'
  what():  command not valid: set_thread_num

**Comment by bupticybee** [comment]
That's a very wired problem, can you submit a sample input file? I'd like to look into this bug.

**Comment by MoonBunnyZZZ** [comment]
> That's a very wired problem, can you submit a sample input file? I'd like to look into this bug.

et_pot 50
set_effective_stack 200
set_board Qs,Jh,2h
set_range_ip AA,KK,QQ,JJ,TT,99:0.75,88:0.75,77:0.5,66:0.25,55:0.25,AK,AQs,AQo:0.75,AJs,AJo:0.5,ATs:0.75,A6s:0.25,A5s:0.75,A4s:0.75,A3s:0.5,A2s:0.5,KQs,KQo:0.5,KJs,KTs:0.75,K5s:0.25,K4s:0.25,QJs:0.75,QTs:0.75,Q9s:0.5,JTs:0.75,J9s:0.75,J8s:0.75,T9s:0.75,T8s:0.75,T7s:0.75,98s:0.75,97s:0.75,96s:0.5,87s:0.75,86s:0.5,85s:0.5,76s:0.75,75s:0.5,65s:0.75,64s:0.5,54s:0.75,53s:0.5,43s:0.5
set_range_oop QQ:0.5,JJ:0.75,TT,99,88,77,66,55,44,33,22,AKo:0.25,AQs,AQo:0.75,AJs,AJo:0.75,ATs,ATo:0.75,A9s,A8s,A7s,A6s,A5s,A4s,A3s,A2s,KQ,KJ,KTs,KTo:0.5,K9s,K8s,K7s,K6s,K5s,K4s:0.5,K3s:0.5,K2s:0.5,QJ,QTs,Q9s,Q8s,Q7s,JTs,JTo:0.5,J9s,J8s,T9s,T8s,T7s,98s,97s,96s,87s,86s,76s,75s,65s,64s,54s,53s,43s
set_bet_sizes oop,flop,bet,50
set_bet_sizes oop,flop,raise,60
set_bet_sizes oop,flop,allin
set_bet_sizes ip,flop,bet,50
set_bet_sizes ip,flop,raise,60
set_bet_sizes ip,flop,allin
set_bet_sizes oop,turn,bet,50
set_bet_sizes oop,turn,raise,60
set_bet_sizes oop,turn,allin
set_bet_sizes ip,turn,bet,50
set_bet_sizes ip,turn,raise,60
set_bet_sizes ip,turn,allin
set_bet_sizes oop,river,bet,50
set_bet_sizes oop,river,donk,50
set_bet_sizes oop,river,raise,60,100
set_bet_sizes oop,river,allin
set_bet_sizes ip,river,bet,50
set_bet_sizes ip,river,raise,60,100
set_bet_sizes ip,river,allin
set_allin_threshold 0.67
build_tree
set_thread_num 10
set_accuracy 0.5
set_max_iteration 200
set_print_interval 10
set_use_isomorphism 1
start_solve
set_dump_rounds 2
dump_result output_result.json


Linux version release
just change  thread num

**Comment by bupticybee** [comment]
> > That's a very wired problem, can you submit a sample input file? I'd like to look into this bug.
> 
> set_pot 50 set_effective_stack 200 set_board Qs,Jh,2h set_range_ip AA,KK,QQ,JJ,TT,99:0.75,88:0.75,77:0.5,66:0.25,55:0.25,AK,AQs,AQo:0.75,AJs,AJo:0.5,ATs:0.75,A6s:0.25,A5s:0.75,A4s:0.75,A3s:0.5,A2s:0.5,KQs,KQo:0.5,KJs,KTs:0.75,K5s:0.25,K4s:0.25,QJs:0.75,QTs:0.75,Q9s:0.5,JTs:0.75,J9s:0.75,J8s:0.75,T9s:0.75,T8s:0.75,T7s:0.75,98s:0.75,97s:0.75,96s:0.5,87s:0.75,86s:0.5,85s:0.5,76s:0.75,75s:0.5,65s:0.75,64s:0.5,54s:0.75,53s:0.5,43s:0.5 set_range_oop QQ:0.5,JJ:0.75,TT,99,88,77,66,55,44,33,22,AKo:0.25,AQs,AQo:0.75,AJs,AJo:0.75,ATs,ATo:0.75,A9s,A8s,A7s,A6s,A5s,A4s,A3s,A2s,KQ,KJ,KTs,KTo:0.5,K9s,K8s,K7s,K6s,K5s,K4s:0.5,K3s:0.5,K2s:0.5,QJ,QTs,Q9s,Q8s,Q7s,JTs,JTo:0.5,J9s,J8s,T9s,T8s,T7s,98s,97s,96s,87s,86s,76s,75s,65s,64s,54s,53s,43s set_bet_sizes oop,flop,bet,50 set_bet_sizes oop,flop,raise,60 set_bet_sizes oop,flop,allin set_bet_sizes ip,flop,bet,50 set_bet_sizes ip,flop,raise,60 set_bet_sizes ip,flop,allin set_bet_sizes oop,turn,bet,50 set_bet_sizes oop,turn,raise,60 set_bet_sizes oop,turn,allin set_bet_sizes ip,turn,bet,50 set_bet_sizes ip,turn,raise,60 set_bet_sizes ip,turn,allin set_bet_sizes oop,river,bet,50 set_bet_sizes oop,river,donk,50 set_bet_sizes oop,river,raise,60,100 set_bet_sizes oop,river,allin set_bet_sizes ip,river,bet,50 set_bet_sizes ip,river,raise,60,100 set_bet_sizes ip,river,allin set_allin_threshold 0.67 build_tree set_thread_num 10 set_accuracy 0.5 set_max_iteration 200 set_print_interval 10 set_use_isomorphism 1 start_solve set_dump_rounds 2 dump_result output_result.json
> 
> Linux version release just change thread num

Thanks I will look into this

**Comment by MoonBunnyZZZ** [comment]
> > > That's a very wired problem, can you submit a sample input file? I'd like to look into this bug.
> > 
> > 
> > set_pot 50 set_effective_stack 200 set_board Qs,Jh,2h set_range_ip AA,KK,QQ,JJ,TT,99:0.75,88:0.75,77:0.5,66:0.25,55:0.25,AK,AQs,AQo:0.75,AJs,AJo:0.5,ATs:0.75,A6s:0.25,A5s:0.75,A4s:0.75,A3s:0.5,A2s:0.5,KQs,KQo:0.5,KJs,KTs:0.75,K5s:0.25,K4s:0.25,QJs:0.75,QTs:0.75,Q9s:0.5,JTs:0.75,J9s:0.75,J8s:0.75,T9s:0.75,T8s:0.75,T7s:0.75,98s:0.75,97s:0.75,96s:0.5,87s:0.75,86s:0.5,85s:0.5,76s:0.75,75s:0.5,65s:0.75,64s:0.5,54s:0.75,53s:0.5,43s:0.5 set_range_oop QQ:0.5,JJ:0.75,TT,99,88,77,66,55,44,33,22,AKo:0.25,AQs,AQo:0.75,AJs,AJo:0.75,ATs,ATo:0.75,A9s,A8s,A7s,A6s,A5s,A4s,A3s,A2s,KQ,KJ,KTs,KTo:0.5,K9s,K8s,K7s,K6s,K5s,K4s:0.5,K3s:0.5,K2s:0.5,QJ,QTs,Q9s,Q8s,Q7s,JTs,JTo:0.5,J9s,J8s,T9s,T8s,T7s,98s,97s,96s,87s,86s,76s,75s,65s,64s,54s,53s,43s set_bet_sizes oop,flop,bet,50 set_bet_sizes oop,flop,raise,60 set_bet_sizes oop,flop,allin set_bet_sizes ip,flop,bet,50 set_bet_sizes ip,flop,raise,60 set_bet_sizes ip,flop,allin set_bet_sizes oop,turn,bet,50 set_bet_sizes oop,turn,raise,60 set_bet_sizes oop,turn,allin set_bet_sizes ip,turn,bet,50 set_bet_sizes ip,turn,raise,60 set_bet_sizes ip,turn,allin set_bet_sizes oop,river,bet,50 set_bet_sizes oop,river,donk,50 set_bet_sizes oop,river,raise,60,100 set_bet_sizes oop,river,allin set_bet_sizes ip,river,bet,50 set_bet_sizes ip,river,raise,60,100 set_bet_sizes ip,river,allin set_allin_threshold 0.67 build_tree set_thread_num 10 set_accuracy 0.5 set_max_iteration 200 set_print_interval 10 set_use_isomorphism 1 start_solve set_dump_rounds 2 dump_result output_result.json
> > Linux version release just change thread num
> 
> Thanks I will look into this, this shouldn't happen

谢谢
请问硬件不变前提下，如何减少计算时间？目前实验来看行动选项和底池筹码比是比较关键因素

**Comment by bupticybee** [comment]
> > > > That's a very wired problem, can you submit a sample input file? I'd like to look into this bug.
> > > 
> > > 
> > > set_pot 50 set_effective_stack 200 set_board Qs,Jh,2h set_range_ip AA,KK,QQ,JJ,TT,99:0.75,88:0.75,77:0.5,66:0.25,55:0.25,AK,AQs,AQo:0.75,AJs,AJo:0.5,ATs:0.75,A6s:0.25,A5s:0.75,A4s:0.75,A3s:0.5,A2s:0.5,KQs,KQo:0.5,KJs,KTs:0.75,K5s:0.25,K4s:0.25,QJs:0.75,QTs:0.75,Q9s:0.5,JTs:0.75,J9s:0.75,J8s:0.75,T9s:0.75,T8s:0.75,T7s:0.75,98s:0.75,97s:0.75,96s:0.5,87s:0.75,86s:0.5,85s:0.5,76s:0.75,75s:0.5,65s:0.75,64s:0.5,54s:0.75,53s:0.5,43s:0.5 set_range_oop QQ:0.5,JJ:0.75,TT,99,88,77,66,55,44,33,22,AKo:0.25,AQs,AQo:0.75,AJs,AJo:0.75,ATs,ATo:0.75,A9s,A8s,A7s,A6s,A5s,A4s,A3s,A2s,KQ,KJ,KTs,KTo:0.5,K9s,K8s,K7s,K6s,K5s,K4s:0.5,K3s:0.5,K2s:0.5,QJ,QTs,Q9s,Q8s,Q7s,JTs,JTo:0.5,J9s,J8s,T9s,T8s,T7s,98s,97s,96s,87s,86s,76s,75s,65s,64s,54s,53s,43s set_bet_sizes oop,flop,bet,50 set_bet_sizes oop,flop,raise,60 set_bet_sizes oop,flop,allin set_bet_sizes ip,flop,bet,50 set_bet_sizes ip,flop,raise,60 set_bet_sizes ip,flop,allin set_bet_sizes oop,turn,bet,50 set_bet_sizes oop,turn,raise,60 set_bet_sizes oop,turn,allin set_bet_sizes ip,turn,bet,50 set_bet_sizes ip,turn,raise,60 set_bet_sizes ip,turn,allin set_bet_sizes oop,river,bet,50 set_bet_sizes oop,river,donk,50 set_bet_sizes oop,river,raise,60,100 set_bet_sizes oop,river,allin set_bet_sizes ip,river,bet,50 set_bet_sizes ip,river,raise,60,100 set_bet_sizes ip,river,allin set_allin_threshold 0.67 build_tree set_thread_num 10 set_accuracy 0.5 set_max_iteration 200 set_print_interval 10 set_use_isomorphism 1 start_solve set_dump_rounds 2 dump_result output_result.json
> > > Linux version release just change thread num
> > 
> > 
> > Thanks I will look into this, this shouldn't happen
> 
> 谢谢 请问硬件不变前提下，如何减少计算时间？目前实验来看行动选项和底池筹码比是比较关键因素

调节一下每条街的下注数量，还有全下阈值都很重要

**Comment by bupticybee** [comment]
This issue is closed because it's inactive for too long. Reopen if necessary.

**Comment by sunlongjian** [comment]
我也是同样的问题
./console_solver -i input.txt
EXEC FROM FILE
[##################################################] 100%
terminate called after throwing an instance of 'std::runtime_error'
  what():
Aborted (core dumped)
用的是这里的示例sample.txt, https://github.com/bupticybee/TexasSolver/tree/console#usage
我的环境是centos7上面的centos8的docker跑的，glibc版本2.28
