### ISSUE TITLE
[not an issue, but question] How to calculate GTO hand ranges

### ISSUE THREAD

**Issue by siarheisinelnikau** [bupticybee/TexasSolver#73]
Hello @bupticybee!
I want to say thank you for such a great project first :)

Maybe that is not a proper place to ask a question - it's about defining hand ranges.
Is there any way to calculate it using your application (for preflop, 3bet, etc.)?
I see some predefined values in config files you have provided, but how to calculate it programmatically?

**Comment by bupticybee** [comment]
It's proper obviously and close related to this project.

No this solver don't provide function to calculate preflop ranges. I use other people's calculation result. 
If you want to calculate preflop range under your own rule, you probably want to check out some other solver (probably the closesourced ones) that contains preflop calculation functions.

Or as I learned communicate to some of the poker-players, they do mentioned some site provide calculated results.
