### ISSUE TITLE
Could you please share the python interface of this work?

### ISSUE THREAD

**Issue by Gridnn** [bupticybee/TexasSolver#78]
You shared [this link](https://github.com/bupticybee/TexasSolver/blob/master/TexasSolverTechDemo.ipynb) in an other issue, but it can not be accessed now. I am a python programmer and highly interested in the work of this area. Could you please share this work in python version? Thank you very much!

**Comment by bupticybee** [comment]
Actually it's now located in the console branch here: https://colab.research.google.com/github/bupticybee/TexasSolver/blob/console/TexasSolverTechDemo.ipynb 

And it's hardly a python interface, it's just a way to call the solver from python. 

Offical python interface was a part of this project before, but was abandoned now.

**Comment by bupticybee** [comment]
Closing because this issue is inactive for too long and considered solved.
