### ISSUE TITLE
Gui faster console

### ISSUE THREAD

**Issue by vpip75pfr3** [bupticybee/TexasSolver#80]
Good afternoon. Thank you for your project! Please can u tell me why the speed of preparing the tree in the gui is much faster than in the console version?
It takes half a second to start counting the distribution in the gui. And in the console version about 10 seconds.

**Comment by bupticybee** [comment]
Beause gui version does the resource loading work in another thread basically. Actually the console version is the faster one.

**Comment by vpip75pfr3** [comment]
As I understand it, in order to calculate the spot in the console version, you need to open the console again every time and enter a command. "console_solver.exe -i resources/text/commandline_sample_input.txt"
And before the calculations start, it takes about 10 seconds for each hand.
That is, if I want to count 40 different rivers, then I will spend about 400 seconds preparing for the calculations, and about 1 second on the calculations themselves.
Or are there any other ways and commands?

**Comment by bupticybee** [comment]
> As I understand it, in order to calculate the spot in the console version, you need to open the console again every time and enter a command. "console_solver.exe -i resources/text/commandline_sample_input.txt" And before the calculations start, it takes about 10 seconds for each hand. That is, if I want to count 40 different rivers, then I will spend about 400 seconds preparing for the calculations, and about 1 second on the calculations themselves. Or are there any other ways and commands?

I actually already considered these kind of requirements.

Yes there are other ways, just launch the console solver without -i and the solver will directly read config from stdin, and you can actually input multiple configs in stdin to achineve similar result that you describe.

**Comment by vpip75pfr3** [comment]
Thank you very much!
