### ISSUE TITLE
大神您好，我已经搞了一个星期了，就是无法成功测试源码

### ISSUE THREAD

**Issue by zhuwuyan2022** [bupticybee/TexasSolver#88]
大神您好，我已经搞了一个星期了，就是无法成功测试源码，请您把 win10 环境下的 编译条件稍微详细的发布一下。
因为我的水平较低，给您带来不便非常抱歉。对于您的技术小弟无比佩服

**Comment by bupticybee** [comment]
如果是编译图形界面版本需要使用开源版本QT 5.1.0，并且使用mingw64作为编译器，然后直接在QT里 build和run就行

**Comment by bupticybee** [comment]
已经好多人编译成功了，代码肯定是没问题的

**Comment by bupticybee** [comment]
This issue is closed because it's inactive for too long. Reopen if necessary.
