### ISSUE TITLE
遇到错误: Card length incorrect: 0 

### ISSUE THREAD

**Issue by shine0nline** [bupticybee/TexasSolver#90]
大神好，win10环境，个把月前一台电脑成功运行并求解。今天下载后成功运行，使用默认参数或者自行选择范围，点击求解后提示：
遇到错误:
Card length incorrect: 0 
另，选择opp或者ip范围不对，例如6max中utg open2.5bb 没有co call的目录
![1(1)](https://user-images.githubusercontent.com/24974280/160156369-09d359fd-3363-4105-9ffd-d71aa75fd3ac.png)

**Comment by bupticybee** [comment]
麻烦导出一份config的txt贴在这里，方便排查

**Comment by shine0nline** [comment]
非常抱歉，是应为没点构建游戏树的原因-_-||

**Comment by bupticybee** [comment]
> 非常抱歉，是应为没点构建游戏树的原因-_-||

好的get
