### ISSUE TITLE
DCFR beta coeff

### ISSUE THREAD

**Issue by diditforlulz273** [bupticybee/TexasSolver#98]
Am I missing something or do you miss DCFR beta round multiplication here:
https://github.com/bupticybee/TexasSolver/blob/02e52e4bb47473d2854626f8c19f26e698c73347/src/trainable/DiscountedCfrTrainable.cpp#L111

I mean, you use a pure beta, not iter_num^beta / (iter_num^beta  + 1), making this correction for alpha_coef some lines before.

**Comment by bupticybee** [comment]
Yes, I see, there seems to be some problem here.
Let me double check whether I make a mistake.

**Comment by bupticybee** [comment]
I checked the code and the paper, the current implementation can be considered correct when β = 0.

In the paper, author says that :

<img width="501" alt="截屏2022-05-03 上午9 20 05" src="https://user-images.githubusercontent.com/9393610/166391633-4da09662-e0f1-46e5-9b8f-399e849dfe46.png">

and at the end of the paper, they says that:

<img width="502" alt="截屏2022-05-03 上午9 20 47" src="https://user-images.githubusercontent.com/9393610/166391682-3107e5b7-cf13-477e-8951-55c6b1b0ca42.png">

So It's easy to see that when β = 0 ,

<img width="50" alt="截屏2022-05-03 上午9 21 12" src="https://user-images.githubusercontent.com/9393610/166391704-643a88d4-db73-45f7-b565-36116b536ce4.png">

always equal to 1/2.

**Comment by diditforlulz273** [comment]
ok, I then guess it is not the first-line thing to fix(as it works correctly in the end), feel free to close this issue.

**Comment by bupticybee** [comment]
> ok, I then guess it is not the first-line thing to fix(as it works correctly in the end), feel free to close this issue.

Okay, closing issue. Feel free to reopen it anytime.
